version: "3.7"
services:
  redis:
    image: redis/redis-stack
    volumes:
      - ~/data/nvb/redis:/data
    ports:
      - 1111:6379
      - 8888:8001
  node-app:
    image: nvb:node
    build:
      context: ./node
      dockerfile: ./Dockerfile
    environment:
      - APP_PORT=3333
      - APP_REDIS_PORT=6379
      - APP_REDIS_HOST=redis
    ports:
      - 3333:3333
    depends_on:
      - redis
  bun-app:
    image: nvb:bun
    build: 
      context: ./bun
      dockerfile: ./Dockerfile
    volumes:
      - ./bun:/app
    environment:
      - APP_PORT=2222
      - APP_REDIS_PORT=6379
      - APP_REDIS_HOST=redis
      - LOG_LEVEL=debug
      - APP_BASE_URL=http://nvb.com
    ports:
      - 2222:2222
    depends_on:
      - redis
  benchmark:
    image: nvb:benchmark
    build:
      context: ./benchmark
      dockerfile: ./Dockerfile
    volumes:
      - ./benchmark:/app
    depends_on:
      - node-app
      - bun-app